runtime: nodejs
env: flex

env_variables:
   CLOUD_SQL_USERNAME: root
   CLOUD_SQL_PASSWORD: microcrm1
   CLOUD_SQL_DATABASE_NAME: microcrm1
   CLOUD_SQL_CONNECTION_NAME: cliosuite-intro:us-east1:microcrm1
   
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
   cloud_sql_instances: cliosuite-intro:us-east1:microcrm1

automatic_scaling:
   min_num_instances: 1
   max_num_instances: 7
